"""add password string to user

Revision ID: 2ce0cf776bb1
Revises: c7e5614c4148
Create Date: 2022-02-06 20:39:24.514639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce0cf776bb1'
down_revision = 'c7e5614c4148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(), nullable=True))
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
