"""add space count and room id

Revision ID: c7213fd5cc99
Revises: 2ce0cf776bb1
Create Date: 2022-02-11 15:59:43.677225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7213fd5cc99'
down_revision = '2ce0cf776bb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_number'):
        op.create_foreign_key('fk_room_book_number_room_id', 'book_number', 'room', ['room_key'], ['room_id'])
        op.drop_column('book_number', 'room_id')
        op.add_column('room', sa.Column('room_space', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_number'):
        op.drop_column('room', 'room_space')
        op.add_column('book_number', sa.Column('room_id', sa.INTEGER(), nullable=True))
        op.drop_constraint('fk_room_book_number_room_id', 'book_number', type_='foreignkey')
    # ### end Alembic commands ###
