"""init migration

Revision ID: c7e5614c4148
Revises: 
Create Date: 2022-01-30 14:33:46.047448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e5614c4148'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_number',
    sa.Column('number_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leaving_date', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('arrival_date < leaving_date'),
    sa.PrimaryKeyConstraint('number_id')
    )
    op.create_index(op.f('ix_book_number_number_id'), 'book_number', ['number_id'], unique=False)
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('role_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_index(op.f('ix_role_role_id'), 'role', ['role_id'], unique=False)
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('price_for_night', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_index(op.f('ix_room_room_id'), 'room', ['room_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_room_room_id'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_role_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_book_number_number_id'), table_name='book_number')
    op.drop_table('book_number')
    # ### end Alembic commands ###
